/*
 * EventTableFrame.java
 *
 * Created on April 13, 2006, 4:51 PM
 */

package cacfdas.model;

/**
 *
 * @author  b4edhdwj
 */

import cacfdas.reachinfo.*;

/** This class is the GUI frame that holds a table that shows the event log of a data band */

public class EventTableFrame extends javax.swing.JFrame {
    
    /** Creates new form EventTableFrame */
    public EventTableFrame(DataBand band, CropInfoTable info) {
        init(band,info);
        initComponents();
        
        setTitle("Event Log for " + info.getInfo(band.getCropNumber()).trim() + 
                " elev " + band.getMinElevation() + " - " + band.getMaxElevation() + 
                " year " + band.getDateList().get(0).dayOfYear() );  
    }
    
    public void init(DataBand band, CropInfoTable info)
    {
        model = new EventTableModel(band,info);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jEventTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jEventTable.setModel(model);
        jScrollPane1.setViewportView(jEventTable);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);

        pack();
    }//GEN-END:initComponents
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jEventTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    /** The table model */
    EventTableModel model;
}
