/*
 * ModelSummaryFrame.java
 *
 * Created on April 21, 2006, 7:55 AM
 */

package cacfdas.model;

/**
 *
 * @author  b4edhdwj
 */

import java.util.*;
import java.io.*;
import java.util.prefs.*;

import cacfdas.reachinfo.*;

public class ModelSummaryFrame extends javax.swing.JFrame {
    
    /** Creates new form ModelSummaryFrame */
    public ModelSummaryFrame(int startYear, ArrayList<HashMap<Integer,ArrayList<DataBand>>> data, CropInfoTable info) {
        init(startYear,data,info);
        initComponents();
        
        
        setTitle("Summary for model results in reach " + info.getHeader().getName() + 
                 " from " + model.getValueAt(0,0) + " to " + model.getValueAt(model.getRowCount()-1,0) );
    }
    
    private void init(int startYear, ArrayList<HashMap<Integer,ArrayList<DataBand>>> data, CropInfoTable info)
    {
        model = new ModelSummaryTableModel(startYear, data,info);
        
        String s = prefs.get("Model Summary Last File","");
        
        if ( !s.equalsIgnoreCase("") )
        {
            lastFile = new File(s);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        op = new javax.swing.JOptionPane();
        fc = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSaveItem = new javax.swing.JMenuItem();
        jSaveAsItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel4, java.awt.BorderLayout.WEST);

        jTable1.setModel(model);
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jSaveItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jSaveItem.setMnemonic('s');
        jSaveItem.setText("Save");
        jSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveItemActionPerformed(evt);
            }
        });

        jMenu1.add(jSaveItem);

        jSaveAsItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jSaveAsItem.setMnemonic('a');
        jSaveAsItem.setText("Save As");
        jSaveAsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveAsItemActionPerformed(evt);
            }
        });

        jMenu1.add(jSaveAsItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-600)/2, (screenSize.height-500)/2, 600, 500);
    }//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if ( saveFile == null )
        {
            int rval = op.showConfirmDialog(this, "Save Table", "Table not Saved", op.YES_NO_OPTION);
            
            if ( rval == op.OK_OPTION )
            {
                saveAs();
            }
            else
            {
                
            }
        }
    }//GEN-LAST:event_formWindowClosing
    
    private void saveAs()
    {
        try
        {
            fc.setSelectedFile(lastFile);
            fc.showSaveDialog(this);
        
            saveFile = fc.getSelectedFile();
            model.writeToFile(saveFile);
            
            lastFile = saveFile;
            prefs.put("Model Summary Last File",lastFile.getAbsolutePath());
        }
        catch (Exception e)
        {
            op.showMessageDialog(this, e.getMessage(), e.getClass().toString(), op.ERROR_MESSAGE);
        }       
    }
    
    private void jSaveAsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveAsItemActionPerformed
        saveAs();
    }//GEN-LAST:event_jSaveAsItemActionPerformed

    private void save()
    {
        if ( saveFile != null )
        {
            try
            {
                model.writeToFile(saveFile);
            }
            catch (Exception e)
            {
                op.showMessageDialog(this, e.getMessage(), e.getClass().toString(), op.ERROR_MESSAGE);
            }
        }
        else
        {
            saveAs();
        }        
    }
    
    private void jSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveItemActionPerformed
        save();
    }//GEN-LAST:event_jSaveItemActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem jSaveAsItem;
    private javax.swing.JMenuItem jSaveItem;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JOptionPane op;
    // End of variables declaration//GEN-END:variables

    ModelSummaryTableModel model;
    File saveFile;
    
    static Preferences prefs = Preferences.userNodeForPackage(ModelSummaryFrame.class);
    static File lastFile;
    
    
}
